Traceback (most recent call last):
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scheen/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/scheen/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy import signal
 
t = np.linspace(0, 1, 1000, endpoint=True)
     
plot(t, signal.square(2 * np.pi * 5 * t))
 
plot.xlabel('t')
plot.ylabel('x(t)')
plot.title('signal rectangulaire')
plot.axhline(y = 0, color = 'k')

plot.show()

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 7[0m
[1;32m      3[0m t [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m1000[39m, endpoint[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m      5[0m plot(t, signal[38;5;241m.[39msquare([38;5;241m2[39m [38;5;241m*[39m np[38;5;241m.[39mpi [38;5;241m*[39m [38;5;241m5[39m [38;5;241m*[39m t))
[0;32m----> 7[0m plot[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mt[39m[38;5;124m'[39m)
[1;32m      8[0m plot[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mx(t)[39m[38;5;124m'[39m)
[1;32m      9[0m plot[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124msignal rectangulaire[39m[38;5;124m'[39m)

[0;31mAttributeError[0m: 'function' object has no attribute 'xlabel'
AttributeError: 'function' object has no attribute 'xlabel'

